### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '7d'

### ISSUE THREAD

**Issue by volneigrams** [janssenlima/ZabbixTuner#13]
Ao Iniciar diagnóstico (item 5 do ZabbixTuner) ele procura pro itens ICMPPING com histórico acima de 7 dias. Mas no zabbix versão 3.4.14 o valor gavado é "7d". gerando um erro no processo. 

File "./ZabbixTuner.py", line 164, in diagnosticoAmbiente
    if int(x["history"]) > 7:
ValueError: invalid literal for int() with base 10: '7d'

**Comment by janssenlima** [comment]
Fixed.
