### ISSUE TITLE
hostids padrao 

### ISSUE THREAD

**Issue by lsa1es** [janssenlima/ZabbixTuner#14]
Tradicionalmento o id do Zabbix Server é o "10084", porem em alguns casos, o usuario recria com outro nome, e o script vai quebrar :/

então seria melhor procurar o host Zabbix Server que contenha o template Zabbix Server ;)

**Comment by fpaternot-zz** [comment]
Como sugere que identifiquemos o zabbix server? Sugere que não seja nem pelo id default nem pelo nome. Qual seria sua sugestão? Consegue enviar o PR?

**Comment by janssenlima** [comment]
Complica porque o usuário pode criar com outro nome também. Poderia criar uma maneira do usuário inserir qual é o host "Zabbix server" e a partir daí, consultar e comparar com o ID retornado. Como é uma coisa específica, espero um PR para validar e empurrar para master.
