### ISSUE TITLE
Erro no modulo

### ISSUE THREAD

**Issue by Filipe-Mariano** [janssenlima/ZabbixTuner#15]
Como resolve esse erro?
![Capturar](https://user-images.githubusercontent.com/11853709/68902835-1b7ce180-0718-11ea-84b1-ad4eebce4912.PNG)

**Comment by fpaternot-zz** [comment]
Me parece ser diferença entre python 2 e 3. O projeto esta um pouco esquecido, mas tente com python 2 e veja se o problema permanece.

**Comment by janssenlima** [comment]
Python3 agora suportado.
[Commit](https://github.com/janssenlima/ZabbixTuner/commit/8597e5c13667b84c71e355244f3b1a1fc8efb87d)
